# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /about
    weight: 20
  - name: User Guide
    url: /user-guide
    weight: 40
    hasChildren: true
  - parent: User Guide
    name: Getting Started
    url:  user-guide/getting-started
    weight: 41
  - parent: User Guide
    name: Examples
    url: user-guide/examples/
    weight: 42
  - parent: User Guide
    name: Theory
    url:  user-guide/theory/
    weight: 43
  - parent: User Guide
    name: Case Studies
    url: user-guide/case-studies/
    weight: 44
  - name: Tools
    url: /#tools
    weight: 30
    hasChildren: true
  - parent: Tools
    name: comet_maths
    url: tools/comet_maths
    weight: 33
  - parent: Tools
    name: obsarray
    url: tools/obsarray
    weight: 32
  - parent: Tools
    name: punpy
    url: tools/punpy
    weight: 31
  - name: News
    url: latest-news
    weight: 50
  - name: People
    url: people
    weight: 60
